### PR TITLE
Adaptive favicon

### PR DESCRIPTION
**Pull request by kwaa**
This PR makes the favicon white in dark mode.

https://web.dev/articles/building/an-adaptive-favicon

### CODE REVIEW

**Comment by kwaa** [comment]
It looks like the changes don't display effectively due to the presence of the `.ico` icon.

**Comment by oscarotero** [comment]
At least in Firefox it doesn't work:
imaxe

But GitHub favicon changes, so there must be a way to do that...

**Comment by kwaa** [comment]
> At least in Firefox it doesn't work

I'm guessing this is because the head also links favicon.ico.

```html
<link href="/favicon.svg" rel="icon" type="image/svg+xml">
<link sizes="16x16 32x32" href="/favicon.ico" rel="icon">
```

**Comment by oscarotero** [comment]
yes, but the svg icon is declared before. In the network panel I see the svg file is downloaded
image

**Comment by kwaa** [comment]
> yes, but the svg icon is declared before. In the network panel I see the svg file is downloaded 

That's weird, I'll try removing favicon.ico and what happens.

**Comment by oscarotero** [comment]
Works like a charm. Thanks!

**Pull request merged**
