### PR TITLE
Improve `/core/loaders` documentation: Mention the Data object returned from the page loaders & add an example

### PR DESCRIPTION
**Pull request by Hallo89**
Hi!

When building a page loader, I noticed that there is no reference as to what needs to be returned from the `loadPages()` callback, so i tried to improve it a bit :) I think the page can be understood better now.
I hope I didn't confuse any data types, so please let me know if I did!

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi! Thanks for this, but there are some aspects in your change that are not fully correct.
You have a fully explanation of how de `Data` object works here: https://lume.land/docs/advanced/the-data-model/

The loader is just a function to load the content and return the `Data` object, but is not responsible of the rendering. Your example of the `toml` loader returning HTML code `<h1>${tomlData.foo}</h1>` is not correct. It must return only the `tomlData` object.

**Comment by Hallo89** [comment]
Oh I see, I will remove that part. But then how would I go about taking the data assigned in `loadPages()` and rendering something from it? Using a processor?

**Comment by Hallo89** [comment]
I see, thanks! I have updated it, I hope everything is correct now :)

**Comment by oscarotero** [comment]
Great. Thank you!

**Pull request merged**
