### PR TITLE
fix: add typescript types

### LINKED ISSUE #60: Use tsx over jsx in documentation
# Summary

```tsx
import type { Data, PageHelpers } from 'lume/core.ts';

export default (
    { title, children }: Data,
    filters: PageHelpers
) => (
  <html>
    <head>
      <title>{title}</title>
    </head>
    <body>
      {children}
    </body>
  </html>
);
```

replace examples in [jsx](https://lume.land/plugins/jsx/), [jsx preact](https://lume.land/plugins/jsx_preact/) with tsx.

## Motivation

majority of template engines lume supports does not have type system (nunjucks, liquid, etc...). however, users of tsx and tsx preact could benefit by using typescript definitions. for example, it would be helpful to show that layouts uses `Data` type.

### PR DESCRIPTION
**Pull request by scarf005**
## Summary

- fixes #60

### Modules

image

### JSX/TSX

image

### CODE REVIEW

**Comment by oscarotero** [comment]
Hey, thanks for this!
But the types in Lume 2 works in different way. `lume/core.ts` no longer exist, and `lume/types.ts` is automatically loaded by Deno (using the deno.json config file).

The page data is in `Lume.Data` and the helpers `Lume.Helpers`. For example:

```ts
export default function (data: Lume.Data, helpers: Lume.Helpers) {
  // Here the code
}
```

**Comment by scarf005** [comment]
Oh, I didn't know that!
Changed the types accordingly.

**Review by oscarotero — APPROVED** [review]

**Comment by oscarotero** [comment]
Okay. Looking at the Deploy preview (https://deploy-preview-93--lumeland.netlify.app/plugins/jsx/) some code tabs are not rendered properly. I think it's because some tags are not closed.

I also think that having both jsx and tsx versions is a bit confusing, because there are two pages and two layouts. I'd keep only one version (TSX) and remove the JSX version.

**Comment by scarf005** [comment]
sure, i'll only keep tsx files.

**Comment by oscarotero** [comment]
Thank you!

**Pull request merged**
